# embed_shaders.cmake
file(WRITE "${OUTPUT_FILE}" "// Auto-generated by CMake. Do not edit!\n")
file(APPEND "${OUTPUT_FILE}" "#pragma once\n\n")
file(APPEND "${OUTPUT_FILE}" "#include <unordered_map>\n#include <string>\n\n")
file(APPEND "${OUTPUT_FILE}" "static const std::unordered_map<std::string, const char*> shaders = {\n")

message(STATUS "Raw SHADERS = ${SHADERS}")
string(REGEX REPLACE " " ";" SHADERS_LIST "${SHADERS}")

foreach(SHADER_PATH IN LISTS SHADERS_LIST)
    get_filename_component(SHADER_NAME ${SHADER_PATH} NAME)

    file(READ "${SHADER_PATH}" CONTENTS)
    string(REPLACE "\\" "\\\\" CONTENTS "${CONTENTS}")
    string(REPLACE "\"" "\\\"" CONTENTS "${CONTENTS}")
    string(REPLACE "\n" "\\n\"\n\"" CONTENTS "${CONTENTS}")

    file(APPEND "${OUTPUT_FILE}" "    {\"${SHADER_NAME}\", \"${CONTENTS}\"},\n")
endforeach()

file(APPEND "${OUTPUT_FILE}" "};\n")
